// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgGridTest: typeof import('./src/components/ag-grid-test.vue')['default']
    BootstrapModel: typeof import('./src/components/bootstrap-model.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VDataTable: typeof import('./src/components/vDataTable.vue')['default']
  }
}
